---
- name: Ensure summary is initialized
  set_fact:
    vmsetup_summary: "{{ vmsetup_summary | default([]) }}"

- name: Display collected summary
  debug:
    msg: "{{ vmsetup_summary | join('\n\n') }}"
  when: vmsetup_summary | length > 0
